### ISSUE TITLE
Añadir sección de Integrantes al Readme

### ISSUE THREAD

**Issue by JoseAConcepcion** [JoseAConcepcion/polyclinic-ml-project#1]
El objetivo de este issue es que practiquen cómo será el flujo de trabajo con las ramas y hacer los correspodientes MR.

- [x] Crear sección Integrantes en el Readme
- [x] José Antonio
- [x] Alejandro
- [x] Melissa
- [x] José Miguel
- [x] Lamela
- [x] Darío

**Comment by Artagos** [comment]
que hago aqui broer??

**Comment by RodryJR** [comment]
mama estoy brillando, baneen a @Artagos
