### ISSUE TITLE
Primera busqueda de papers para el estado del arte

### ISSUE THREAD

**Issue by Artagos** [JoseAConcepcion/polyclinic-ml-project#11]
# Primera búsqueda del estado del arte
- Encontrar Papers relevantes para nuestro tema

**Comment by JoseAConcepcion** [comment]
1. [https://ieeexplore.ieee.org/document/9619334](https://ieeexplore.ieee.org/document/9619334)
2. [https://pmc.ncbi.nlm.nih.gov/articles/PMC7219401/](https://pmc.ncbi.nlm.nih.gov/articles/PMC7219401/)
3. [https://ieeexplore.ieee.org/document/9225319](https://ieeexplore.ieee.org/document/9225319)
4. [https://pmc.ncbi.nlm.nih.gov/articles/PMC7362800/](https://pmc.ncbi.nlm.nih.gov/articles/PMC7362800/)
5. [https://www.sciencedirect.com/science/article/pii/S096007792030518X](https://www.sciencedirect.com/science/article/pii/S096007792030518X)
6. [https://link.springer.com/article/10.1007/s42600-020-00105-4](https://link.springer.com/article/10.1007/s42600-020-00105-4)
7. [https://www.liebertpub.com/doi/abs/10.1089/big.2020.0159](https://www.liebertpub.com/doi/abs/10.1089/big.2020.0159)
8. [https://ieeexplore.ieee.org/abstract/document/8742529](https://ieeexplore.ieee.org/abstract/document/8742529)
9. [https://onlinelibrary.wiley.com/doi/abs/10.1111/joes.12429](https://onlinelibrary.wiley.com/doi/abs/10.1111/joes.12429)
10. [https://jamanetwork.com/journals/jamanetworkopen/article-abstract/2712176](https://jamanetwork.com/journals/jamanetworkopen/article-abstract/2712176)
11. [https://dl.acm.org/doi/full/10.1145/3531326](https://dl.acm.org/doi/full/10.1145/3531326)
12. [https://www.mdpi.com/2571-9394/3/1/12](https://www.mdpi.com/2571-9394/3/1/12)
