### ISSUE TITLE
Crear la tabla de papers

### ISSUE THREAD

**Issue by Artagos** [JoseAConcepcion/polyclinic-ml-project#18]
- Ir rellenando una tabla con los papers que vayamos analizando

**Comment by josem-nex** [comment]
Analizar la propuesta, eliminar o añadir filas

**Comment by josem-nex** [comment]
https://github.com/JoseAConcepcion/polyclinic-ml-project/blob/develop/papers_SOA/00_Propuestas%20de%20tabla.md
